### ISSUE TITLE
Create CSV import function

### ISSUE THREAD

**Issue by ocrasborn** [Woseseltops/signbank#33] opened 2015-01-19 14:45 UTC
• Import a CSV file in the same format as the CSV export button generates
• Replacing only changed values, matching on the basis of the ID number (first column)
• Generating a list of changed and unchanged "Annotation ID Gloss: Dutch"s that can be saved

**Comment by Woseseltops** [comment] 2015-01-29 17:07
Note to self: I've ignored everything which is not a simple model field for now.

**Comment by Woseseltops** [comment] 2015-01-30 13:43
The basic functionality for this now works: I've exported some signs to a CSV, made some changes, and imported the CSV again, and the changes were executed. 

However, there are still a number of corner cases to take care of. Some notes: 
* If you export all signs and import them again, the change detector will crash because some choice fields are still empty in the database. 
* If haven't tested the change detector for all types of fields yet.
* Fields that reference other parts of the database (like translations) are ignored for now.

**Comment by Woseseltops** [comment] 2015-02-04 13:08
As far as I can see, this now fully works for simple fields. There are two steps still to be taken, but I'm not sure how important it is to do them now - let me know:

* Some fields do not contain actual content, but relations to other parts of the database, like to which language a gloss belongs, or the translations (=relation to keyword). If you edit those in the CSV, the import won't notice.

* I haven't tested this for every possible change, so I wouldn't be surprised if there were still some corner cases left that don't work or spawn errors. With exporting and importing a whole database with all kinds of different fields, there's a lot that can go wrong.

**Comment by ocrasborn** [comment] 2015-02-11 15:31
It appears that boolean fields are not exported in the CSV export; does anything need to be changed in the import module for that as well?

**Comment by Woseseltops** [comment] 2015-02-12 09:13
I fixed this two weeks ago :) https://github.com/Woseseltops/signbank/commit/fcd93798801ed765abffce332650443990a5575c Could it be the case that you are using an older export? And if not, what fields are we talking about?

**Comment by richardbank** [comment] 2015-02-13 15:47
In some (not all) cases, replacing a value in a multiple choice field with ' ' (whitespace) results in a machine value that is identical to the gloss. For example in the gloss 'test5':
For test5, Initial Primary Location changes from Above head (38) to (None).
For test5, Weak Hand changes from R (47) to (test5).

**Comment by richardbank** [comment] 2015-02-13 16:12
A more comprehensive test (where I changed all fields to whitespace) reveals that the above behaviour only occurs with the Weak Hand field.

**Comment by Woseseltops** [comment] 2015-02-25 13:16
It required some hard thinking, but I think I figured this one out: your problem probably wasn't the Weak Hand field itself, but the fact that you put in a space instead of nothing. I added support for spaces to indicate empty fields, does that fix your problem?

**Comment by ocrasborn** [comment] 2015-04-02 21:50
Re: Wessel's comment of Febr 4: please do allow import of relations to other parts of the database. In particular, relations to Keywords are important, as this is a field that we will regularly want to modify in an exported version (that will be imported back), to ensure consistency.

**Comment by richardbank** [comment] 2015-04-10 12:21
When adding functionality for importing Keywords, please make sure this will be case-sensitive.

**Comment by Woseseltops** [comment] 2015-04-15 10:29
The main functionality works, but I didn't look into case-sensitivity yet.

About case-sensitivity: after some thinking I've come to the realization it's not that straightforward how exactly 'import keywords in a case-sensitive way' should work. Let's agree on this before it build it. It's going to take some text to explain all of this, so brace yourself :).

First, you should understand that the whole import mechanism works with two algorithms:
1. The change detection algorithm compares the whole string of keywords. So if something has the keywords 'one', 'two' and 'three', and 'four' is added, it will compare the string 'one, two, three' to 'one, two three, four'. If a change is detected, this is given to the update algorithm (if the user agrees).
2. The update algorithm will throw away the current relations between the gloss that is being updated and the keywords, and then go over each of the keywords in the new string. For each keyword in the list, it tries to find a keyword in the database that has exactly the same text, and creates a relation to it if it finds one. If it can't find a keyword that matches, it creates a new keyword, and creates a relation to it.

My proposal would be to make these simple changes:
* For the detection algorithm, temporarily make both strings completely lowercase before comparison. This means that a change like 'one, two' to 'ONE, TWO' but also 'amsterdam' to 'Amsterdam' won't be detected.
* Make the search for existing keywords case-insensitive, which means that it will simply link to the first keyword it finds with the same letters. 

These proposals have the following consequences:
* When a keyword is removed from a gloss, it will remain in the total list of keywords. This is because you only remove the relation. If you want it to be removed completely, it can be removed in the Django admin.

* When a keyword is added, it will be added exactly as it was given. So if we get 'aMSTERDAM', 'aMSTERDAM' will be added. 

* There is no such thing as 'changing' keywords. If you change the letters of a keyword, it will be recognized as a new keyword (while the old one still exists in the database), whereas if you only change whether something is upper or lowercase, it won't do anything.

A thing to consider: this is quite a lot of work for (what I expected to be) a non-important feature. You might also consider to leave the system case-sensitive as it is now.

**Comment by Woseseltops** [comment] 2015-04-15 13:13
Note: in the above, I assumed the current system is case-sensitive, and you want it to be canse-insensitive, but according to @ocrasborn it's actually the other way around. The above is still relevant for the discussion, though, but some things might be confusing ;).

**Comment by richardbank** [comment] 2015-04-17 14:25
Regarding case: the current system is indeed case-sensitive, and good as it is.

Two remaining issues:
- *For WAAR-D, Keywords changes from waar (waar) to 1 (1).*
    In WAAR-D, 'waar' is the only keyword, and it is imported as boolean 'true'. This does not happen when 'waar' is part of a comma separated string, e.g. WAAR-C 'echt, waarheid, waar'

- Importing a selection of columns works tot the extent that you always need a dummy column at the end for changes in the second to last column to take effect. Example:
    - importing SignbankID, StrongHand changes nothing, even if values in Stronghand have changed
    - importing SignbankID, StrongHand, WeakHand only changes values in StrongHand, even if values in WeakHand also have changed
    - et cetera
This is circumvented by including a column that includes no changes (e.g. Gloss), but that shouldn't be necessary.

**Comment by Woseseltops** [comment] 2015-04-23 08:17
As for your first remaining issue; I cannot reproduce it:

For WAAR-D, Keywords changes from test (test) to waar (waar).

Any hints on what I should do?

**Comment by Woseseltops** [comment] 2015-04-23 08:32
The second problem is fixed now: the problem was that there was a linebreak character at the end of the line with the keys. So in your example, the algorithm tried to find a field with the name 'StrongHand\r', which didn't exist, so it ignored it.

**Comment by richardbank** [comment] 2015-04-24 14:32
It appears that 'waar' was represented as boolean 'true' in the excel-file that formed the basis for the csv-import. Sorry for the inconvenience...

**Closed by richardbank** 2015-04-24 14:32 UTC
Labels: enhancement, top priority
